### ISSUE TITLE
Riscrittura in un linguaggio più serio

### ISSUE THREAD

**Issue by foxyseta** [csunibo/raccoglitesi#3]

**Comment by Flecart** [comment]
Ho iniziato a fare qualcosina in go, aperto un altro branch.

**Comment by Flecart** [comment]
@foxyseta la workflow funziona, ma l'output ha ancora qualche problema, il tex non compila.
In particolare per la sezione "Tutti" (quindi possiamo fixare o a livello `saveLatex` o a livello `getTesi`), le regex non riescono a togliere gli spazi, end lines e tab, cosa molto strana. Riusciresti a darci un occhiata per sto pezzo??
