### ISSUE TITLE
Generare un file HTML al posto di un PDF

### ISSUE THREAD

**Issue by VaiTon** [csunibo/raccoglitesi#7]
Si potrebbe fare senza troppi cambiamenti, utilizzando Pandoc.

Nel lungo andare consiglierei di generare un file in AsciiDoc o Markdown, e da li produrre l'html.

**Comment by foxyseta** [comment]
@csunibo/esperti-composizione-documenti a chi interesserebbe lavorarci? Io potrei essere disponibile ma non nelle prossime settimane

**Comment by cristian-5** [comment]
forse verso settembre ma adesso è impossibile per me

**Comment by VaiTon** [comment]
Implementato in f4938646d1bf97e5c66a08f2673a13d221f157de
